# Generated by Django 6.0.3 on 2026-06-04 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('lessons', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='branches.group'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='students.student'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='branches.subject'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='lessontemplate',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_templates', to='branches.group'),
        ),
        migrations.AddField(
            model_name='lessontemplate',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_templates', to='students.student'),
        ),
        migrations.AddField(
            model_name='lessontemplate',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_templates', to='branches.subject'),
        ),
        migrations.AddField(
            model_name='lessontemplate',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='lessons.lessontemplate'),
        ),
        migrations.AddField(
            model_name='lessontemplateslot',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='lessons.lessontemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('lesson', 'student')},
        ),
        migrations.AddConstraint(
            model_name='lessontemplate',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='lessontemplate_start_date_before_end_date'),
        ),
        migrations.AddConstraint(
            model_name='lessontemplate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('student__isnull', False), ('group__isnull', True)), models.Q(('student__isnull', True), ('group__isnull', False)), _connector='OR'), name='lessontemplate_student_or_group_only'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('start_datetime__lt', models.F('end_datetime'))), name='lesson_start_datetime_before_end_datetime'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('student__isnull', False), ('group__isnull', True)), models.Q(('student__isnull', True), ('group__isnull', False)), _connector='OR'), name='lesson_student_or_group_only'),
        ),
        migrations.AddConstraint(
            model_name='lessontemplateslot',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='lessontemplateslot_start_time_before_end_time'),
        ),
        migrations.AlterUniqueTogether(
            name='lessontemplateslot',
            unique_together={('template', 'weekday', 'start_time', 'end_time')},
        ),
    ]
